#!/usr/bin/env python3

import argparse
import datetime
import os
import sys
import re

timestr = datetime.datetime.now().strftime("%f")
defaultjob = 'a2c_[TIMESTRING]'

parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('--jobname', help='A name for the qsub job (max 10 chars)', type=str, default=defaultjob)
required = parser.add_argument_group('required arguments')
required.add_argument('--note', help='A short note to add to the log file', type=str)
args = parser.parse_args()

if args.note == None:
	parser.print_help()
	sys.exit()

if args.jobname == defaultjob:
	args.jobname = "a2c_{}".format(timestr)
elif not re.match(r'^\w+$', args.jobname):
	print("Invalid job name: {}".format(args.jobname))
	sys.exit()

script_body='''#!/bin/sh
#
#  Request 1 GPU
#$ -l gpus=1
#
#  Request 8 CPU cores
#$ -pe smp 8
#

cd ~
source tf-py3-gpu-env.sh
cd ~/dev/mean-a2c
./run-atari --note="{}" --num_cpus=8
'''.format(args.note)

os.makedirs("scripts/", exist_ok=True)

jobfile = "scripts/{}".format(args.jobname)

with open(jobfile, 'w') as f:
	f.write(script_body)

cmd="qsub {}".format(jobfile)
print(cmd)
os.system(cmd)
